### ISSUE TITLE
MK-555: UI Component listing all contacts

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#2306]
Jira issue originally created by user @kazoompa:

Currently, the combo that lists the existing contacts shows a maximum of 10 people. Similar to LinkedIn or Facebook, another UI component is required to show all existing contacts.

**Comment by meek0** [comment]
following #3817

Person management and relationships are centralized.

Must manage person index on person deletion. If a person is deleted in the database, one would also need to purge that person from elasticsearch (person index AND person in published/draft study and network indices).
The published state of the study and network documents is a blocker.
