### ISSUE TITLE
MK-1090: Search: The download button for the tab List must use stream with no/very high limit

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#2802]
Jira issue originally created by user @firone:

In the case of MR, downloading 700K variables gives only the first 100K ones.
Instead of that, if no limit is specified in the query, the resource should iterate search requests until all the documents have been extracted and make a file to download of it.

**Comment by ymarcon** [comment]
Hard coded limit:
https://github.com/obiba/ng-obiba-mica/blob/master/src/search/components/result/search-result/component.js#L82

**Comment by meek0** [comment]
PR #3645 is related.
