### ISSUE TITLE
Taxonomy indexing not functional in upgrade task 

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3566]
Despite a taxonomy update event is launched after taxonomy modification in upgrade task, it appears that the re-index was not effective. Is it a cache issue?

https://github.com/obiba/mica2/blob/master/mica-core/src/main/java/org/obiba/mica/core/upgrade/Mica330Upgrade.java#L60

**Comment by kazoompa** [comment]
I just installed 3.2.5 and the upgraded to 3.3.1 and the search worked. May be the indexing delay was much longer. In any case, when deploying we monitor the ES servers, Mongo to guarantee correct functionality. Clonsing...
