### ISSUE TITLE
Bug on re-index taxonimies in mica server

### ISSUE THREAD

**Issue by smirfolio** [obiba/mica2#3577]
Maelstrom site -> The scale: "John_brown_test" is removed from opal taxonomies editor: Mlstr_cogscale -> Cog_scale After re-index taxonomies / dadates, it seems that, it's not removed from taxo rql builder list (in the search page): "Constructs for cognitive functioning" same problem with "Letter_Fluency" FFQ is in the " illicit drugs" scale

**Comment by smirfolio** [comment]
It may be not a bug, after re-index the variables, the term was removed from the  taxo rql builder list (in the search page)

**Comment by ymarcon** [comment]
Is it a bug? If not, close it.
