### ISSUE TITLE
Cart - Add Checkboxes to variable search result table

### ISSUE THREAD

**Issue by meek0** [obiba/mica2#3614]
Checkboxes will be used to select subset of variable identifiers to be added to the cart.

Select variables and give it to the "Save to Cart" component.

**Comment by ymarcon** [comment]
Storing variable IDs in the browser DB does not cale. That is why the current implementation of the cart is to create a set of variables in ES and store in the browser DB the ID of this set. Any set can then be used in search queries (already implemented).

**Comment by kazoompa** [comment]
### TODOs:
- try to reuse selection decorator for Set detail pages.
- complete adding selections when _allSelected_ is _true_.
- remove scope dependency of SearchResult component, this requires a change to AddToSet directive by not depending on a selection list in the parent scope.
- implement selections for other documents
