### ISSUE TITLE
Search page Variable property  searching by population

### ISSUE THREAD

**Issue by smirfolio** [obiba/mica2#3619]
**Describe the bug**
search by population property in variable panel don't return result, the generated query : search?query=variable(match(string:1,Mica_variable.populationId))
It may be more efficient if the search include name/acronym populations instead searching in Id, or as DCE panel search have checkBox of populations 

![image](https://user-images.githubusercontent.com/1859345/51702050-caf99380-1fe0-11e9-826a-54eca3309750.png)

**To Reproduce**
1. Go to 'Search page'
2. Click on 'Variable property panel'
3. Scroll down to 'Population'
4. Enter a population id, name ... in the input box
5. hit enter
4. the result display 0 items

**Expected behavior**
the attached variable list to the selected population 

**Screenshots**
![image](https://user-images.githubusercontent.com/1859345/51702209-33e10b80-1fe1-11e9-825d-97ae943f06e2.png)

**Additional context**
Reported bay obiba-user : https://groups.google.com/forum/#!topic/obiba-users/_9u7MoSBR7U

**Comment by sam-story** [comment]
This would be really useful functionality as there is currently no way to search on the population.
