### ISSUE TITLE
Wildcard searching inconsistent

### ISSUE THREAD

**Issue by sam-story** [obiba/mica2#3628]
When searching free text vocabularies the * wildcard is removed from the main search box
E.g. searching for a*b just does a search for ab

![image](https://user-images.githubusercontent.com/34068523/52789103-e47b8180-305a-11e9-8bd5-8272c51fd1b0.png)

The a*b search is possible as it can be entered via the url e.g.
https://www.maelstrom-research.org/mica/repository#/search?type=variables&display=list&query=variable(match(a*b,Mica_variable.name))

It would be useful if the wildcard is not removed

Also when searching free text custom taxonomies the match is an exact match whereas the built in taxonomies do a contains match.

E.g. 
https://www.maelstrom-research.org/mica/repository#/search?type=variables&display=list&query=variable(match(ab,Mica_variable.name))
does a search for any Mica_variable.name that contains ab 

https://www.maelstrom-research.org/mica/repository#/search?type=variables&display=list&query=variable(match(ab,custom_taxonomy.name))
does a search for any custom_taxonomy.name that is exactly ab

**Comment by kazoompa** [comment]
The first problem is fixed and will be committed soon. As for the second problem, this is more complicated as custom taxonomies are not configured to be indexed with an analyzer. There is a plan to enhance the taxonomy configuration and indexing altogether. This feature enhancement has not been fully analyzed and scheduled. We can inform as soon as a decision is made.
