### ISSUE TITLE
Schedule old sets cleaning

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3658]
In order to avoid sets count to grow, schedule a background task in the server to be run every day, and that cleans the old sets. An old set is identified by comparing the last modified date with a configured  number of days.

* add a mica server configuration to allow specifying the number of days a set can live before being automatically removed. Default is 1 year.
* update the "lastModifiedDate" property each time a set is queried individually:
```
GET /variables/set/{id}
GET /variables/set/{id}/documents
GET /variables/set/{id}/documents/_export
```

**Comment by meek0** [comment]
Wouldn't it be better to separate "time to live" for lists and carts?

**Comment by ymarcon** [comment]
Good idea, even if ALSPAC is planning to use carts only, there could be different time to live.
