### ISSUE TITLE
Suggest set name on new set saving

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3659]
The name of the set must be representative of the search query display. On possibility is to use the criteria components display name to make the set full name (don't need to specify the AND/OR conjunctions):

_Bitrth place | Education, Alcohol, Quality of life_

![image](https://user-images.githubusercontent.com/2581149/53640463-8c34aa00-3c2c-11e9-9112-fe0d1bc96400.png)

**Comment by kazoompa** [comment]
I am not sure this is a good idea for the following reasons:
- length of the name
- localization cannot be ignores and could make the names weird and very long

I would let the user have a go at it.

**Comment by ymarcon** [comment]
I am sure it is a good idea to **suggest**. User is free to simplify the naming afterwards.
