### ISSUE TITLE
Individual Studies Included tables all have 0 variables for each cohort

### ISSUE THREAD

**Issue by smirfolio** [obiba/mica2#3673]
**Describe the bug**
In the harmonisation project / harmonised dataset  detail page the included studies tables show no variables in correspondent study 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  Harmonised dataset / Harmonisation project detail page 

**Expected behaviour**
The  count variable on the studies table have to be consistent 

**Screenshots**
Harmonised Dataset studies table : 
![image](https://user-images.githubusercontent.com/1859345/54216653-6f1b9900-44c0-11e9-85b5-e4af842237b0.png)

Harmonisation Project detail page : 
![image](https://user-images.githubusercontent.com/1859345/54216756-a5591880-44c0-11e9-9637-f2a2cdd5dbbd.png)

**Additional context**
It can be a consequence or a cause of this issue on the search when querying the PATH study for example the result show no variables

**Comment by meek0** [comment]
Removed the Variable column (using config).
