### ISSUE TITLE
Notifications shows {0} if there is no title yet

### ISSUE THREAD

**Issue by tdemalliard** [obiba/mica2#3686]
**Describe the bug**
Notifications like now documents and comments show ```"{0}"``` as the application name when there is no title yet written by the user.

**To Reproduce**
1. create a new application without a title
2. save
3. go to comment section of this application
4. write a new comment
5. see the notification with ```"{0}"````

**Expected behavior**
The notification email could use the application number if there is no title defined yet.

**Screenshots**
![image](https://user-images.githubusercontent.com/3911087/55080046-cc444c80-5073-11e9-8e11-2463748d053f.png)

**Desktop (please complete the following information):**
 - mica2, agate and drupal-mica up to date

**Comment by ymarcon** [comment]
And a quote is missing: "daccès" => "d'accès"

**Comment by tdemalliard** [comment]
I did the correction. Here are my notes for single quotes: to get one single quote in emails, one must:
* type 2 single quote for title and body
* type 1 single quote for details
