### ISSUE TITLE
Quotes raise error in Mica filter text box

### ISSUE THREAD

**Issue by sam-story** [obiba/mica2#3689]
After entering double quotes in the in filter text box for Network, Studies or Datasets the following error is displayed:
all shards failed (500)

See screenshot for example
![image](https://user-images.githubusercontent.com/34068523/55237500-343c9380-522a-11e9-9b6e-3d9dca9907a9.png)

**Comment by kazoompa** [comment]
We should apply the same sanitation as in the search page.

**Comment by sam-story** [comment]
I think this is a low priority but would be good to fix at some point.

**Comment by sam-story** [comment]
I think this is a low priority but would be good to fix at some point.
