### ISSUE TITLE
Taxonomic Vocabularies with spaces don't link in classification graph

### ISSUE THREAD

**Issue by sam-story** [obiba/mica2#3690]
If a classification vocabulary has a space in the name the link on the link on the variable classification graph on the variable details page is not formed correctly.

![image](https://user-images.githubusercontent.com/34068523/55386818-36ec0100-5528-11e9-900f-abe52ec46cbe.png)

Clicking on a bar image will direct the user to the search page, however there is an issue with the url encoding
https://alspac-data.bristol.ac.uk/mica-web/mica/repository#/search?query=variable(and(exists(Closer_Topics.Mental%20health%20and%20mental%20processes),in(Mica_variable.datasetId,c)))&display=list&type=variables

For some reason %20 is not interpreted correctly. The page loads but no search criteria is applied. If it the %20's are replaced with %2520 then it works fine.

Brackets in the vocabulary name also cause problems and I haven't been able to resolve these.

An alternative fix would be to prevent certain characters when setting up the name in Opal. All Maelstrom vocabulary names use underscore in place of space

**Comment by meek0** [comment]
Newly created taxonomy vocabularies shouldn't have this problem anymore.
