### ISSUE TITLE
Incorrect Links on the Coverage tab

### ISSUE THREAD

**Issue by sam-story** [obiba/mica2#3691]
On the Variables details page, if the Coverage tab is set up to display the Population and DCE the links are not as expected.

Clicking a DCE link loads the study page, population section, I would expect it to load the DCE popup.  
![image](https://user-images.githubusercontent.com/34068523/55404898-d9b87580-5550-11e9-81dd-9da21e6c7f12.png)

The same thing happens when clicking the Population link (e.g. the study page is loaded displaying the population section). This is more expected, but it would be better to keep it consistent with other parts of the system where the Population popup is displayed.

**Comment by meek0** [comment]
The link works well for the portal but not for mica.
Tried with [this link](https://mica-nightly.maelstrom-research.org/#/search?query=variable(or(in(Mlstr_area.Sociodemographic_economic_characteristics,Age),in(Mlstr_area.Lifestyle_behaviours,Alcohol)))&display=coverage&bucket=dce) and clicking on a dce link redirects to the home page.

**Comment by ymarcon** [comment]
Please test otherwise it is closed automatically
