### ISSUE TITLE
Exiting Search Textbox does not apply criteria

### ISSUE THREAD

**Issue by sam-story** [obiba/mica2#3698]
Enter a value in the Name Search, and tab or Mouse click to the Label search. Enter a value in the Label search and press Enter 

![image](https://user-images.githubusercontent.com/34068523/56048110-bbb3f780-5d3e-11e9-88b7-4d333028f11f.png)

After pressing Enter the Label criteria is applied but the Name criteria is not and is dropped.

![image](https://user-images.githubusercontent.com/34068523/56048404-5c0a1c00-5d3f-11e9-834e-c0ee4ebc3f4d.png)

It is not obvious that pressing Enter is required or that you need to press it for each text criteria. I think it would be better to apply the criteria on the on-exit event of the text box.

**Comment by sam-story** [comment]
I tested this on Chrome (v73) and IE 11

**Comment by sam-story** [comment]
I think this is an important one to fix as it affects the user experience.

**Comment by kazoompa** [comment]
I don't think leaving an inputbox should affect the search, you could be leaving the control to add something else and before you know it a search has been executed. May be we can add an search icon or a help text to make it clear an ENRER is required to initiate the search.

**Comment by sam-story** [comment]
The main problem is the criteria being dropped. 

As long as all criteria that has been added is applied when the ENTER button is pressed, then this would solve the problem. E.g. in my example 
The user enters a name criteria and then a label criteria, they press enter when in the label criteria, and this applied both the Name and the Label. (Currently it just applied the Label and drops the Name).

**Comment by kazoompa** [comment]
We should apply filter upon closing and not ignore the text query.
