### ISSUE TITLE
Acronym change dans le fichier download

### ISSUE THREAD

**Issue by fsanogo** [obiba/mica2#3699]
**Describe the bug**
L'acronym de l'étude 10/66 est modifié quand on fait un download

**To Reproduce**
1. Selectionne socio-demo
2. aller à list puis variables
3. Faire download
4. l'acronym 10/66 devient Oct-66

**Expected behavior**
L'acronym ne devrait pas changer

**Comment by meek0** [comment]
Can't reproduce, the csv file does contain the "10/66" acronym. Problem might be due to the application used to open the csv.

In plain text, it is exactly as it should.
