### ISSUE TITLE
Help text for Search Filter page

### ISSUE THREAD

**Issue by sam-story** [obiba/mica2#3701]
Using Layout 2

Following feedback from our users lots of people were confused about how to return to the search results. They did not realise that they could click on the buttons at the top of the page. 
 
Having some help text at the top of the page that could be edited via Mica Translation would be very useful. Adding an information icon and having an additional popup description would provide further of flexibility for administrators customising the help.

![image](https://user-images.githubusercontent.com/34068523/56200479-cfa97300-6036-11e9-9a85-859d31154ac8.png)

**Comment by ymarcon** [comment]
It is possible to replace the cross icon by a more explicit button. See how it appears in Maelstrom web site:
![image](https://user-images.githubusercontent.com/2581149/56211857-1740f680-6059-11e9-9a67-1aa3546bb218.png)

@smirfolio can you explain how to do this?

**Comment by kazoompa** [comment]
To do as in Maelstrom portal site, you must override the template in this
file: vocabulary-filter-detail-heading-component.tpl.php. Here is an
example:

The default:

...
        <div class="col-xs-12 col-sm-1 col-lg-1">
            <button type="button"
                    class="voffset1 pull-right close"
                    data-dismiss="alert"
                    aria-label="Close"
                    ng-click="$ctrl.togglePannel()"
                    title="{{'global.close-panel'|translate}}"><span
aria-hidden="true">×</span>
            </button>
        </div>

The overridden version:

...
        <div class="col-xs-12 col-sm-2 col-lg-2 voffset1">
            <button type="button"
                    class="voffset1 btn btn-xs btn-success pull-right"
                    data-dismiss="alert"
                    aria-label="Close"
                    ng-click="$ctrl.togglePannel()"><span
aria-hidden="true" translate>global.close-panel</span>
            </button>
        </div>

Once this is done, you can go to translation and change the caption for
this the key global.close-panel or a key of your own.

I admit, this kind of customization needs an enhancement *massage*!

Ramin

**Comment by sam-story** [comment]
Thanks Ramin,
I haven't been able to find the file "vocabulary-filter-detail-heading-component.tpl.php" 

I have found the code you refer to in the file "/var/www/html/mica-web/sites/all/libraries/angular-app/ng-obiba-mica/src/search/components/vocabulary-filter-detail-heading/component.html"

I have tried creating the file "vocabulary-filter-detail-heading-component.tpl.php" in my sub theme template folder, but I think I'm still missing some steps. Does the templates.php file need to reference this new file or am I going off on the wrong track?

Thanks,

Sam

**Comment by kazoompa** [comment]
Hi Sam,

In your sub theme project, try to place the file under the following path
as depicted in this snapshot:

[image: image.png]

This is the Maelstrom sub theme folder structure.

Ramin

**Comment by kazoompa** [comment]
Yes, forgot that part:

Snippet to add in `template.php`:
```php
    'vocabulary-filter-detail-heading-component' => array(
      'template' => 'vocabulary-filter-detail-heading-component',
      'path' => $angular_app_theme . '/search/components'
    ),
```

**Comment by sam-story** [comment]
Thanks Ramin,

I ended up putting the template file in "/templates/vocabulary-filter-detail-heading-component.tpl.php" and tweaked your code snippet to add the file check round it.

  $destination_path = file_exists($path . '/templates/vocabulary-filter-detail-heading-component.tpl.php');
  if (!empty($destination_path)) {
    $theme_array['vocabulary-filter-detail-heading-component'] = array(
      'template' => 'vocabulary-filter-detail-heading-component',
      'path' => $path . '/templates',
    );
  }

It's working now, thank for your help
