### ISSUE TITLE
Not Authorized Error on DAR Access

### ISSUE THREAD

**Issue by meek0** [obiba/mica2#3707]
**Describe the bug**
A user can no longer access their DAR. Observed with DAR''s only for now, but after creation the user can no longer access the DAR by id. This means that any action requiring the DAR's id will be unauthorized.

[These lines](https://github.com/obiba/mica2/blob/master/mica-rest/src/main/java/org/obiba/mica/access/rest/DataAccessRequestResource.java#L94-L95) seem to have no effect such that the id remains null no matter what.

**To Reproduce**
1. Log in as a mica-user
2. Create a DAR
3. Get Unauthorized Error message

**Expected behavior**
The user should be able  to access the DAR that was created.

**Additional context**
This currently only  affects the master. No released version is problematic.
The problem is  similar to https://github.com/obiba/mica2/pull/3703 and seems to be related to https://github.com/obiba/mica2/pull/3702

**Comment by ymarcon** [comment]
@meek0 solved?

**Comment by meek0** [comment]
solved by #3709
