### ISSUE TITLE
Document's Lists of Investigators/Contacts are no Longer Sortable

### ISSUE THREAD

**Issue by meek0** [obiba/mica2#3710]
**Describe the bug**
It seems that one could sort items in a document's list of investigator or contacts using a "drag and drop" feature. It is no longer possible to do so.

**To Reproduce**
1. Go to a document with more than on investigator or contact
2. Hover over an investigator or contact line 
3. Do the drag and drop motion to move that line up or down the list

**Expected behavior**
Should be able to move the item.

**Additional context**
Currently a problem on master and the latest 3.5.x release at least.

**Comment by ymarcon** [comment]
@smirfolio  @meek0  is it fixed?

**Comment by meek0** [comment]
not fixed

**Comment by kazoompa** [comment]
we should also fix #3686
