### ISSUE TITLE
Bug on list Download button

### ISSUE THREAD

**Issue by smirfolio** [obiba/mica2#3716]
**Describe the bug**
The variable count on the downloaded csv files is different from Variable count on the same list

**To Reproduce**
1. Go the the search
2. Make a query exp: select Tobacco or Alcohol term 
3. Select all variables from result table
4. Add the selected variable to a list
5. Download all the variables from the selected List 
6. Open the the Dowloaded csv file 

**Expected behavior**
The count of downloaded variable have to the same in selected list

**Additional context**
Test on the Default seed data

**Comment by meek0** [comment]
It seems that the csv writer does not trim values. It will take the white space characters as is.
