### ISSUE TITLE
Download opal views corresponding to selected variables in the cart/list

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3737]
Following #3627, the opal views button ignores the variables that could have been selected in the cart/list. This is confusing because the variable list download behaves differently.

**Comment by meek0** [comment]
As mentioned before, thematically this feature would not be tied to a set anymore.
It would mean that one could provide a list of "identifiers" and download it as views (be it from the search page or anywhere where one could find variable identifiers).

Is that okay? if so, the button could be added to the search page instead and the query  or selections would be the basis of the download.

**Comment by ymarcon** [comment]
No Opal-views download in the search page, it's for advanced users.
