### ISSUE TITLE
Errors encoding accent in mongo databases 

### ISSUE THREAD

**Issue by tdemalliard** [obiba/mica2#3748]
**Describe the bug**
Names with accent are not set properly in some databases, leading to error if they were set outside of mica2 (mongo shell)

**To Reproduce**
1. Create a user name with an accent in name
2. Create an access request with this user
3. look in collection agate/User for the name
4. look in collection mica/dataAccessRequest for the applicant : wrong accent

**Expected behavior**
Names should be the same in all collections, using mongo shell or a mongodb editor.

**Screenshots**
agate/user:
![image](https://user-images.githubusercontent.com/3911087/61804691-5920cc00-ae02-11e9-8637-a386e443599e.png)

mica/dataAccessRequest:
![image](https://user-images.githubusercontent.com/3911087/61804744-781f5e00-ae02-11e9-8eed-33bfe4f01f2b.png)

**Server:**
- mongoDB v4.0.10
- Mongo editor used: NoSQLBooster for MongoDB v5.1.8
- mongo shell used: the client installed with mongoDB v4.0.10

**Additional context**
Usernames where changed manually with 'sed'. Accounts with accent in username could not display their data access requests.

**Comment by kazoompa** [comment]
This is not Mica specific error, this is a limitation of JPA not taking of accents. Quick solution is to disallow accents in usernames. Otherwise we have to write our own queries using Mongo Template and take care the accents. I have rarely seen a username with accents... to be decided.
