### ISSUE TITLE
Geographical Distribution graph

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3770]
* Rename column Studies to Number of Studies
* Add sorting to both columns (Country and Number of Studies) - alphabetical ascending and descending
* Add an asterix under the image: Multiple countries can be associated with one study. (text to be verified by the ST)

**Comment by smirfolio** [comment]
Add sorting :
https://docs.angularjs.org/api/ng/filter/orderBy

**Comment by sofiyad** [comment]
1) Do not include the Harmonisation studies in the graph, the distribution should always have the same number as the total 
For example in IALSA https://portal-staging.maelstrom-research.org/mica/network/ialsa - N=125, Total in table - 124 
The graph should display 124 as well.

2) Columns in table should have the same width
