### ISSUE TITLE
Number of Participants graph

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3772]
* Change the Colors from light to dark based on the number of studies
* Add Percentage of Studies column
* Add totals

**Comment by meek0** [comment]
![image](https://user-images.githubusercontent.com/6180385/66230610-90d5ab00-e6b2-11e9-89c9-d1ecae07defc.png)

**Comment by sofiyad** [comment]
1) Order of Number of participants column is incorrect. Also, every network should have the same categories even if the result in some of them is 0.

less than 1,000
1,000 to 4,999
5,000 to 9,999 
10,000 to 49,999
50,000 to 99,999 
100,000 to 499,999 
500,000 and more
undetermined

2) The new row undetermined will include all studies that are not listed, for example IALSA has 124 Ind.studies but only 116 are listed. The 8 missing ones should be in the category "undetermined"

3) Include the actual number of participants column that is shown in the Study design and Study Start Year graphs. Make sure all columns are the same width.
