### ISSUE TITLE
New graph #1 - Start Year

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3775]
Same design as Number of Participants

5 to 9 categories based on the bell curve (@guifabre to use Mica R and give the normal distribution of all start dates)
<1900
1901 - 1950
1951 - 2000
2001 - 2010
> 2010

**Comment by kazoompa** [comment]
This is fixed but not QA-ed yet.

**Comment by sofiyad** [comment]
1) Change categories to:

before 1950
1950 to 1959
1960 to 1969
1970 to 1979
1980 to 1989
1990 to 1999
2000 to 2009
2010 and after

2) Columns have to be the same width

3) Number of participants column (without the title) should be aligned to the left
