### ISSUE TITLE
New graph #2 - Duration of Follow-up

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3777]
Design - double donut as @smirfolio suggested.

Two types of duration:
1) Start and End date (end date - start date)
2) Ongoing (current year - start date)

Categories based on normal distribution 0 to ~60
0 - 5
6 - 10
11 - 15
16 - 20
20+

**Comment by kazoompa** [comment]
1) Can be added while indexing the study as study_duration
2) This cannot be since the current date is always changing and this cannot be indexed, unless we use scripts when indexing - not too efficient for indexing time.
