### ISSUE TITLE
Q: Does mica support external openid proider (i.e. keycloak)?

### ISSUE THREAD

**Issue by redmitry** [obiba/mica2#3782]
Hello,
I understand that Opal can work with Keycloak as identity provider.
Can mica2 do the same?

We'd like to use Opal + Mica2 + Keycloak. Is this configuration possible?

Thank you,

Dmitry

**Comment by ymarcon** [comment]
Not exactly: it's Agate that works with Keycloak. Agate still provides user management services to Mica2 whereas Keycloak is just a ID provider. Then the possible configuration is: Opal + Mica2 + Agate + Keycloak.

**Comment by redmitry** [comment]
Thank you, Yannick!
We just configured Opal with Keycloak, but since Mica2 needs Agate, it looks more reasonable to use Agate for Opal also.

Yours sincerely,

Dmitry
