### ISSUE TITLE
Confirm the addition of sub-domain, not domain in Variables->Scales

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3784]
Currently in Search ->Variables ->Scales/Measure when you add Criteria to the search you get confirmation for the Domain only, when you add two sub domains no confirmation for the second at all.
Change to receive confirmation for each sub domain.

From Julie: pop-up des sous-domaines au lieu des domaines. La boite de dialogue devrait confirmer l'ajout de variable / scale plutôt que l'aire d'info exemple"Criteria lifestyle and behaviors variable was added." ou "Criteria Constructs for.. was added."

**Comment by meek0** [comment]
Requires changing the condition and value of the "growl". 
Due to the complexity of the search module, estimate: **1d**
