### ISSUE TITLE
Improve the min and max age search

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3785]
pop-up faire textes pour range, improve the search by range 
Clarifier ce qu'il faut mettre dans l'interval proposé pour l'âge maximum ou minimum. 
Peut-être des termes plus explicites pour DataSchema variables ?

**Comment by kazoompa** [comment]
Needs a bit of clarification.

**Comment by sofiyad** [comment]
Define ranges

**Comment by meek0** [comment]
The only notation that is erroneous seems to be the `between` notation, we are actually using `[x,y]` notion and not the one that is shown currently (`[x,y)`).

The range term query uses `[x,y)`.
The others (`ge` and `le`) are self-explanatory.
