### ISSUE TITLE
Alphabetic order of scales

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3786]
Afficher les scales par ordre alphabétique de nom et pas acronyme

//L'ordre est déterminé dans Opal et il ne faut pas le changer dans Mica.

**Comment by sofiyad** [comment]
Drop down in Opal for sorting

**Comment by kazoompa** [comment]
The problem here is that taxonomies are localized, i.e., there may be two locales EN or FR. How to save the sort order? That is the question.

**Comment by meek0** [comment]
If this must be done client side, the variable taxonomy configuration page must include the opal taxonomies (mostly read-only) such that the order can be configured.

**Comment by sofiyad** [comment]
The task was for scales only, could you please reverse the changes for areas of information, source, and target asap. Thanks! @meek0

**Comment by kazoompa** [comment]
May be add a attribute in the Taxonomy of Taxonomies YAML file to set the desired sort.
