### ISSUE TITLE
Add asterisk to explain how the search works - AND, multiple criteria, etc.

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3787]
Confirm with Isabel first.

Add asterisk to explain how the search works - AND, multiple criteria, etc.

**Comment by meek0** [comment]
Documentation could be based on [lucene's text search](http://lucenetutorial.com/lucene-query-syntax.html).

Must add the same text in mica (and opal?)'s documentation.
Estimate: **1d**

**Comment by meek0** [comment]
tentative text:
```
Basic Search: Documents returned will match one or more words.
Exact Phrases: Use double quotes to search for an exact phrase.
Exact Words: Use the "+" operator to search for the exact word in a document.
Exclude Terms: The "-" operator allows you to remove all documents containing a word from the result.
Logic: The "AND" and "OR" operators can be combined to match documents against boolean logic.
```

also need to find where to put it.
