### ISSUE TITLE
Automatic reminders for annual and final reports

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3792]
Automatic reminders: email notification for annual reports and the final report sent to
researchers.

Notes:
* start date is to be identified: approved date, field in the DAR form, separate field?
* could the notifications be disabled for a specific DAR?
* should the reception of a report be validated by the DAO? (so that a notification is not triggered when not relevant)
* for a specific event, should the system send a single notification email or multiple ones (1 month before the dead-line, then 1 week etc.)?

**Comment by tdemalliard** [comment]
1. Start date : shoud start when the contract is signed by the institution and the researcher. End date in a field in the DAR.
1. Disabled for specific DAR: we will discuss that tomorrow.
1. Yes, DAO will validate the report
1. Multiple notificatiobns: we will discuss that tomorrow

**Comment by ymarcon** [comment]
@tdemalliard any info from your discussions?

**Comment by tdemalliard** [comment]
2. No DAR will required disabled notification as these DAR wont have a signed contract date.

4. multiple notification would be nice, upon reception of the report.

**Comment by ymarcon** [comment]
* start date: date field not included in the form (because the real start date is not necessarily the one declared in the form), visible only if the DAR has been approved and editable only by the DAO.
* end date: a field in the DAR form, which can be overridden by a field in the Amendment form.
* history of events should include notification emails
* one notification email per event (one-year reports and final report)
* number of days before deadline should be configurable
* notification email should be different depending it is intermediate or final report (switch in the email template, parameter to be passed)
* DAR submission progress bar to be replaced by a timeline with expected report dates

**Comment by ymarcon** [comment]
Timeline template in HTML+CSS:
https://codepen.io/Nuwen/pen/NGwEXV
