### ISSUE TITLE
 Improve DAR print layout

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3793]
Improve print layout to make it user-friendly for reviewers. The final goal is to have a document that can be attached to a contract and then only the selected options should appear in this layout, to improve the readability. 

* Add the submission or acceptance date to the access request when printing it
* Hide choices not selected in multiple choice lists
* Display on the same line question and the answer if it is a yes/no answer question

**Comment by tdemalliard** [comment]
Also, could the print/export date added?

**Comment by ymarcon** [comment]
* inline field: value is inlined with the title of the field
* hide checkboxes that are not checked
* inline radio/dropdown
* hide title+field when no value
* js/css script to allow form rendering customization?
