### ISSUE TITLE
 Improve sorting of applications in access request table

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3794]
Improve sorting of applications in access request table so the Data Access Officer can
easily detect modified application requests.

**Comment by tdemalliard** [comment]
We would like the default sorting to be by "last update" date instead of "creation date" (wich is not even aviable as a column). This will allow the DAO to detect easily which projects are moving forward and which projects are stalling.

**Comment by ymarcon** [comment]
Default sorting is to be one of columns, that makes sense.
