### ISSUE TITLE
Additional welcome page to display following login

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3796]
This page will give information to the researcher about Data Access Requests. 
Is it just a block visible to some group of users in the general welcome page?

**Comment by tdemalliard** [comment]
The pre-login page invite to create an account or login, and contain some usefull links. Then the post-login page invite to a new DAR, or display the list of DARs, and contain some usefull links.

I see it more like a new page, than a new drupal block wich appear, but could be if on block is displayed only when not logged, then the other one is displayed.

The main target is researcher. It would be great for future (help for the DAC) if there could be many blocks role-specific. But only one block would be enough for now.

Thinking of the drupal block, and your role question : this could be role specific as login user is a drupal role.

**Comment by ymarcon** [comment]
Related to #3833 the home page should have in its context some statistics about the data access requests (nb of created for applicant, nb of pending for dao etc.).

**Comment by ymarcon** [comment]
Please reopen if still relevant with the template infrastructure.
