### ISSUE TITLE
Improve hybrid input content detection

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3797]
Improve hybrid input content detection in online forms (to make content match with what was previously entered, e.g. checked “Projects has co-PI” then name of co-PI should be entered in appropriate field”).

**Comment by ymarcon** [comment]
* input field should be disabled when not checked
* on uncheck, empty input field
* label should be attached to the check

**Comment by ymarcon** [comment]
@tdemalliard is an input field value is required when the check is selected, or is it optional?

**Comment by tdemalliard** [comment]
This is more for the section _5 - Biological samples_. The researcher should choose the samples he wants and indicate the volume ne needs. Both are require, we need to know how much of the sample the researcher needs:
![image](https://user-images.githubusercontent.com/3911087/72353125-7ea3d980-36b1-11ea-930a-082e2000db46.png)

For the co-Pi section, the checkbox is not required as it is asking if the co-Pi should access the data.
![image](https://user-images.githubusercontent.com/3911087/72353183-a09d5c00-36b1-11ea-823c-0b4ba885998e.png)
