### ISSUE TITLE
Possibility to add custom entries (links) to the main menu

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3798]
Most likely it is a Drupal theme thing.

**Comment by tdemalliard** [comment]
When installing mica-drupal, had several issues with the menu and the multilingal system of drupa. This is why we have this request.

**Comment by ymarcon** [comment]
* review menu definition in mica drupal module
* make a module per study for altering menu (and other hooks)?
* help with translation

**Comment by ymarcon** [comment]
The #3833 solves this issue by using a templating system.
