### ISSUE TITLE
Standardize display between DAO and Data Access Committee

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3799]

**Comment by tdemalliard** [comment]
We would like the DAC to have a "Registered users" menu entry and be allowed to access it:

![image](https://user-images.githubusercontent.com/3911087/67579526-a585eb80-f712-11e9-8978-e649b597a1e3.png)

**Comment by ymarcon** [comment]
@tdemalliard  Is these "Registered users" are really only the ones who just registered (even without activity) or are the ones that have some associated data access request?

**Comment by smirfolio** [comment]
The Registered Users seen by a DAO are only the one that have some associated data access request,as data access requests manager, you can affect  to a DAC user an DAO role (Group), it will be a kind of role heritation, as long as all DAO group actions are permitted to DAC group

**Comment by tdemalliard** [comment]
@smirfolio got it right. The way we are working with the DAC is that it is a custom group we have created as you explained us when we have installed together our Obiba softwares this year.

It is important for SDAC to know what ongoing and closed projects a research has with us. If so, there can be implications.

**Comment by ymarcon** [comment]
DAC members to have access to the list of users having a DAR (without having the additional privilegies of a DAO).

**Comment by ymarcon** [comment]
I would need more info about this Data Access Committee: this role does not exist in Mica server. What are the expected rights of these users?
