### ISSUE TITLE
Feasibility Inquiry Form module

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3800]
* Add the Feasibility Inquiry Form prepared by CPTP
* Auto-generate the Letter of Support from a template and using the data entered with the Feasibility Inquiry Form

**Comment by tdemalliard** [comment]
This a new form that researcher could **optionnaly** fillin **before** the application form in in order to obtain a letter of support for a grant. This letter could be autogenerate from a template once approved by the DAO. In this scenario, the project code should be generate along with this form and keept when the researcher continue with the application form.

I will upload the CPTP Feasibility Inquiry Form as soon as I obtain it from CPTP.

**Comment by ymarcon** [comment]
* are these inquiry forms associated to a Data Access Request context?
* what are the status of these forms? looks like the DAO can approve, then there should be a submission etc.
* are there email notifications associated to the events that would happen on each of the inquiry form instance?
* after DAR form is submitted, should the inquiry form be disabled?

**Comment by ymarcon** [comment]
* see example of [myatpresearch.ca/](https://myatpresearch.ca/) feasibility form
* feasibility form should be part of a DAR object
* review DAR page layout because it is becoming more and more complex (feasibility, application, amendments). Maybe instruction text (in markdown) could be associated to each type of form and displayed aside of it
* define a life cycle for this form (submit, review...)

**Comment by tdemalliard** [comment]
no automatic letter sent as a scientific director should sign the letter before sending it to the researcher. So the life cycle is:
1. researcher submits
1. DAO accepts, reject or re-open
1. DAO display the letter, print it to a PDF, send it to scientific director for signature
1. DAO upload the signed letter in the document section and/or send it to the researcher

We would like notifications. Could the notifications be disabled via mica admin panel ?

**Comment by ymarcon** [comment]
Every notifications can be enabled/disabled from the admin panel.

**Comment by tdemalliard** [comment]
Letter of support should be issued at any state of an application as it could be needed for an application or an amendment.

**Comment by ymarcon** [comment]
Issue #3833 addresses the layout of the DAR, so that the Feasibility Inquiry Form can be added.
