### ISSUE TITLE
make study design field mandatory to publish

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3811]
Make study design field mandatory to publish a study.
Once done re-assign the task to me (@sofiyad ) so we can fix existing studies.

**Comment by kazoompa** [comment]
Just a note, making a field mandatory applies to saving a study not publishing. This change will imply that you cannot create or edit a study without setting the design field.

**Comment by kazoompa** [comment]
One more point, it would be great to find out whether there are other fields to become mandatory.

**Comment by kazoompa** [comment]
Follow these steps to make this change for Mlstr:

- Go to `/admin/individual-study-config`
- In the Schema TAB you will see the current setting as:
```json
    "methods": {
      "type": "object",
      "title": "t(study.design)",
      "properties": {
        "design": {
          "type": "string",
          "title": "t(study_taxonomy.vocabulary.methods-design.title)",
          "enum": [
            "cohort_study",
            "case_control",
            "case_only",
            "cross_sectional",
            "clinical_trial",
            "other"
          ]
        },
 ```
- Add `"required": true,` to make this field mandatory
- Save the changes and wait until the Study taxonomies are indexed (one min is more than enough)

Corrected setting:
```json
    "methods": {
      "type": "object",
      "title": "t(study.design)",
      "properties": {
        "design": {
          "type": "string",
          "title": "t(study_taxonomy.vocabulary.methods-design.title)",
          "required": true,
          "enum": [
            "cohort_study",
            "case_control",
            "case_only",
            "cross_sectional",
            "clinical_trial",
            "other"
          ]
        },
```
