### ISSUE TITLE
Amendment sorting is not working

### ISSUE THREAD

**Issue by tdemalliard** [obiba/mica2#3826]
**Describe the bug**
Sorting by 'Pending amendments' and 'Total amendments' is not working

**To Reproduce**
1. Login as DAO or researcher on mica client
2. display 'My Data Access Requests'
3. click on 'Pending amendments' and 'Total amendments'
4. no sorting occure

**Expected behavior**
Sorting should work

**Screenshots**

**Desktop (please complete the following information):**
- ubuntu 16.04 with chrome up to date
- Mica Client 7.x-36.5

**Comment by meek0** [comment]
Seems to be an issue with Chrome browser. Works on Firefox.
Need to investigate.

**Comment by tdemalliard** [comment]
I confirm that it works with firefox (ubuntu)
