### ISSUE TITLE
When searching within a network to be able to search for datasets only from this network. 

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3840]
When searching within a network to be able to search for  only from this network. Gray out / disable options that will not return results.

Choose a network (Reach for example)
Then open Variable -> Properties. Choose any dataset (for example 10-66_Cuba_Followup) No variables will be found. 10-66_Cuba_Followup has to be disabled so the user cant select it.

**Comment by meek0** [comment]
This sounds like a facets (in our case using aggregations).
This might be very costly and might slow down the page.
Else the only way to achieve this is by using aggregations (we do have a great number of vocabularies).

Need to analyze more.

**Comment by kazoompa** [comment]
I do not think this can be done in either version of elasticsearch 2 or 7.
