### ISSUE TITLE
Export Study description to a text file

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3841]
Add an option to export a study description - fields and values, to a text file.

**Comment by meek0** [comment]
A long term solution (with maybe import in mind) could be that we export the study to csv.
Using [xpath](https://github.com/json-path/JsonPath) to build the `key` and exposing the value, we could have a minimum of two columns: `field` and `value`. 

If need be the `title` could be added.

Estimate: **3d**

**Comment by sofiyad** [comment]
To discuss with Isabel

**Comment by meek0** [comment]
A plus is the potential for the exported CSV file (path, value) created to be imported back into the study to apply modifications.

An example path would be: `$['model']['methods']['info']`.
