### ISSUE TITLE
wysiwyg editor for the text fields in the form

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3843]
wysiwyg editor for the text fields in the form

**Comment by meek0** [comment]
Quick fix would be to add a preview button to the schemaform textarea, similarily to how we do for comments related to #2703.
Else use [a simple wysiwyg editor](https://github.com/sparksuite/simplemde-markdown-editor) in schemaform.

**Comment by kazoompa** [comment]
Our Comments textarea in Mica looks like this except the button on the left, we could use that.

![image](https://user-images.githubusercontent.com/2814716/74254894-1865a300-4cbf-11ea-9f03-03d1745a8b68.png)

**Comment by meek0** [comment]
We should also make sure that the `marked` library's version supports the latest GFM addition (notably the check list).

**Comment by ymarcon** [comment]
The simplemde looks good.
Be aware that it should apply to localized text as well.

**Comment by sofiyad** [comment]
To discuss options with Isabel

**Comment by ymarcon** [comment]
I have integrated simplemde to the data access request comments and it's pretty cool. Try it: https://mica-test.obiba.org/data-access-comments/264320

**Comment by sofiyad** [comment]
looks great @ymarcon !
