### ISSUE TITLE
Validation of large Data Access Request form

### ISSUE THREAD

**Issue by StuartWheater** [obiba/mica2#3845]
I am specifying a Data Access Request form which has 125 fields. I have split the form into 18 tabs, to split the form into sections. I have started specifics validation for the fields, and I was wondering if it is possible to determine the all required fields within the "tabs" section are provided and are valid?
I would like to provide a visual indication when a section is complete.
Regards, Stuart

**Comment by ymarcon** [comment]
The form validation applies to the whole form. When a field is in error, the "has-error" css class is applied. I am not sure there is a way of triggering a custom script (that would inspect the fields that are identified as being in error) on validation event, maybe @meek0 or @kazoompa know.

**Comment by StuartWheater** [comment]
Thank you. I was hoping it was possible to apply a "has-error" type css class to the "tab label" for the section. Thanks again, Stuart

**Comment by kazoompa** [comment]
I think one way to do this is to define your required fields per `properties` each property corresponding to a TAB. 

For example:

```json
    "staff": {
      "type": "array",
      "maxItems": 5,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "type": "string"
          },
          "title": {
            "title": "Title",
            "type": "string"
          },
          "position": {
            "title": "Position",
            "type": "string"
          },
          "email": {
            "title": "Email",
            "type": "string",
            "pattern": "^\\S+@\\S+$"
          }
        },
        "required": [
          "name",
          "email"
        ]
      }
    }
```

Here is the so so [documentation](https://github.com/json-schema-form/angular-schema-form/blob/master/docs/index.md.)

**Comment by StuartWheater** [comment]
kazoompa, thank you for this suggestion. I have tried to restructure my scheme to match this style, but with limited success. I will try to start with a simpler scheme. Stuart
