### ISSUE TITLE
Hide the Harmonization variables column

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3862]
Hide the Harmonization variables column in the Studies table. 

https://www.maelstrom-research.org/mica/repository#/search?type=studies&display=list

**Comment by sofiyad** [comment]
![unnamed](https://user-images.githubusercontent.com/51130016/76238572-6ca06c00-6206-11ea-8ea1-a0b935aee161.png)

**Comment by meek0** [comment]
current condition to show this column: `choseHarmonization && (optionsCols.showStudiesHarmonizationDatasetsColumn || optionsCols.showStudiesDataschemaVariablesColumn)`

where `choseHarmonization` is whether or not only study type searched is `all` or `harmonization`.
the rest is derived from drupal's configuration.

**Comment by smirfolio** [comment]
It's a Drupal configuration under : 
configurations --> Search settings --> Studies search --> STUDY COLUMN DISPLAY SETTINGS section disable the Show dataschema variables
