### ISSUE TITLE
Add harmonization status in the MR taxonomy

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3881]
Add another harmonization status in the MR taxonomy.
The status will be "Not applicable" and the definition is "Not relevant to evaluate harmonization potential".

In the opal data dictionary, we assign harmonization status' in the column Mlstr_harmo::status and this is what makes the checkmarks and x's appear in the harmonization potential table:
https://www.maelstrom-research.org/mica/harmonized-dataset/mindmap_1_01

**Comment by ymarcon** [comment]
How will it be rendered in the Mica's harmo table? we already have icons for complete (/), impossible (x) and undetermined (?).

**Comment by sofiyad** [comment]
Completed

**Comment by ymarcon** [comment]
This "na" term has not been added to the source of the taxonomy:
https://github.com/maelstrom-research/maelstrom-taxonomies/blob/master/Harmonization.yml

**Comment by smirfolio** [comment]
Not sur if it's a general case to implement, the code implemented in Drupal fetech any Harmonization status (Not hard coded any more)
Also I implemented the default values on installation that reflet the default harmonization status in the taxonomy : https://github.com/obiba/mica-drupal7/pull/1724/files#diff-55f65fa34b1a231bb532150c490cf42bR635

**Comment by ymarcon** [comment]
Anything that is Drupal specific is not part of Mica.

**Comment by kazoompa** [comment]
The only thing missing is to translate in FR so other users of Mlstr Taxos have a correct YAML.

**Comment by ymarcon** [comment]
Could someone do this FR translation ? Should not be long.

**Comment by kazoompa** [comment]
@sofiyad can we ask Rita to add translation for FR so I can download and push the latest version o Github for a new release?

**Comment by sofiyad** [comment]
sent an email to Rita and Isabel

**Comment by ymarcon** [comment]
Translation still pending.

**Comment by sofiyad** [comment]
This is what Rita has so far, but it is not approved by Isabel yet

statut: non-applicable, définition: non-approprié d'évaluer le potentiel d'harmonisation
