### ISSUE TITLE
Harmonization Dataset Index Mechanism

### ISSUE THREAD

**Issue by meek0** [obiba/mica2#3883]
Currently, when indexing harmonization datasets, Mica will store all variables (dataschema and harmonized) on the heap which can and will slow down the application.

It would be preferable to send out as soon as a size threshold has been reached or similar to avoid storing millions of variables before indexing

**Comment by kazoompa** [comment]
It would be nice to use [Arthas](https://github.com/alibaba/arthas) tool for memory usage analysis.

**Comment by kazoompa** [comment]
[Implemented resolution](https://github.com/obiba/mica2/pull/3974) iterates through each study table of a harmonized dataset and indexes the associated variables.
