### ISSUE TITLE
Unable to serve mica2 pages from sub-directory of web-site

### ISSUE THREAD

**Issue by StuartWheater** [obiba/mica2#3896]
**Describe the bug**
I am unable to serve mica2 pages from sub-directory of web-site, due to not being able to specify baseURL.

**Expected behavior**
If you examine the contains of the pages obtained the styling content is expected to be below "/".

**Desktop (please complete the following information):**
 - Browser: All
 - Version: 4.0

**Additional context**
I tried to make changes to the configure page, but they didn't seem to address the issue.

Stuart

**Comment by kazoompa** [comment]
Hi Stuart,

Did you try to customize a page? If so, take a look [here](http://micadoc.obiba.org/en/latest/admin/pub-configuration.html) for more information.

If it's not a customized page, could provide more information about the folder and which page is the problem?

Ramin

**Comment by ymarcon** [comment]
This is not a bug, only the sub-domain use case is handled: mica.example.org but not www.example.org/mica. Can you switch to a sub-domain setup?

**Comment by StuartWheater** [comment]
At present the VM I am using for MICA demonstration is also used for other web applications.
I well request another VM so I can solo deploy.

Thanks for the help.

Stuart

**Comment by ymarcon** [comment]
You can still use the same VM and discriminate using subdomains + apache + let's encrypt. For instance mica-demo.obiba.org and mica-test.obiba.org run on the same VM.

**Comment by StuartWheater** [comment]
I was wondering about asking if the University could set-up a CNAME. I will
investigate...
Thanks.
Stuart

>
