### ISSUE TITLE
Entity Revision Comparison

### ISSUE THREAD

**Issue by kazoompa** [obiba/mica2#3901]
[ ] Use Git module in obiba-commons to compare the Study CSVs to flag differences

To investigate how to represent the differences in UI:

1- simple side-by-side diff of the JSON paths
2- show the DIFFs in the UI using a CSS

Estimated time: 3W (depending on the UI strategy)

**Comment by meek0** [comment]
Will use google guava's `MapDifference` data structure.
Need to flatten to object before getting the differences.

Need to find a way to map those fields to their respective title.
Strategy could require parsing the documents schema and definition (jsonpath could be a good tool).

Tentatife UI could consist of three tables side by side showing the differences between "right", "both" and "middle". 

Will elaborate later.

**Comment by meek0** [comment]
Guava's [difference utility](https://github.com/google/guava/wiki/CollectionUtilitiesExplained#difference) couple with "flattening" a json reprsention of the model (using jsonpath) works well.

Problem would be to link fields with their title.
Initial solution would be to filter out those titles from the document's schema. Mandatory fields (as well as custom ones) would need further processing.

This review comparison feature would be coupled with the history tab. Could replace the view history with a "view diff with current" and/or "view diff with previous".
