### ISSUE TITLE
Import studies from remote Mica instances

### ISSUE THREAD

**Issue by zeornelas** [obiba/mica2#3904]
**Is your feature request related to a problem? Please describe.**
In the context of one of the projects that I'm participating in, we've several partners that have installed Mica instances in their IT infrastructure. In the scope of those projects, these partners collaborate in different studies, which they describe using Mica functionalities. Some of these studies are being used by more than one partner, they want to be able to keep local copies of the study descriptions (including its populations and data collection events). To accomplish that, they want to be able to import the study descriptions from remote Mica instances where they have credentials.

**Describe the solution you'd like**
The solution should encompass the following steps:
- an import button should be added to the platform;
- an import modal appears when clicking on the import button;
- the import modal asks the URL and credentials for the remote Mica instance;
- the import process checks if the Mica instances use the same - schemas/definitions (for studies, populations and data collection events);
-if the schemas are the same, the user can select which of the remote studies are imported;
- after that, the user is presented with a summary table stating which actions will be performed (create - if the remote study does not exist locally; update - if the remote study exists locally).

**Describe alternatives you've considered**
- One alternative that we considered was to use the Mica Python client to export from one Mica instance and then import the result into another instance. However, the idea is for the actual end-users to be able to import studies and so the ideally this should be achieved using the Mica web application;
- Reusing the existing endpoint "/draft/studies/_import". However, it would presuppose sending zip files with specific folder structures, contrasting with the idea to achieve this through the Mica web application.

**Additional context**
No comments.

**Comment by rljoia** [comment]
The Pull Request for this issue [is done](https://github.com/obiba/mica2/pull/3906), but I don't have write access for merge pull requests. I suppose that maintainers have all permissions to evaluate it.

I'm not sure if it's expected, but I applied the Pull Request for master branch target. If you have any questions or suggestions about it, please comment.

**Comment by ymarcon** [comment]
Thanks, for this PR, this is the regular process (PR on master, review by maintainers).

**Comment by kazoompa** [comment]
I am closing this issue as it is merged into the master branch.
