### ISSUE TITLE
Make the Authorization field in Mica as array

### ISSUE THREAD

**Issue by smirfolio** [obiba/mica2#3976]
**Is your feature request related to a problem? Please describe.**
In the Authorization section we can not add more then one Authorizer

**Describe the solution you'd like**
Add a "Add Authorization" Button for both "Maelstrom catalogues" and "[specific network] catalogues"

![image.png](https://images.zenhubusercontent.com/5b0c09eda281cf5395ef5177/c4b04ec0-1b0c-4db2-8104-606530c14866)

**Comment by sofiyad** [comment]
duplicate
