### ISSUE TITLE
cannot see items if label is missing

### ISSUE THREAD

**Issue by joerghenkebuero** [obiba/mica2#3977]
**Describe the bug**
I can upload a data dictionary as provided in the template but without a label for a variable. The import works, also creating the opal tables in the opal application works. But as I want to use that dictionary in MICA, loading the variables does not work. Therefore, the label field is mandatory, but the upload process in opal doesn't check that.

To Reproduce
Upload a damaged opal template dictionary to opal, create a study in mica and add that opal data dictionary to the study. Try to browse the study variables.

In Mica, I get this javascript error:

TypeError: "summary.variableLabel is undefined"

Expected behavior
Mica loads what is available instead of trying to load endless what is not there.

Desktop (please complete the following information):

    OS: doesn't matter
    Browser: doesn't matter, but I used firefox
    Version: the current one

This issue is related to https://github.com/obiba/opal/issues/3582

**Comment by kazoompa** [comment]
I was not able to reproduce the bug following these steps:

- Imported a dictionary below in Opal
- Created a test Study and Dataset in Mica
- Published both documents, the later bringing the corresponding variables from Opal
- Did a search and selected the corresponding study
> No errors in the console

Can you specify the Mica version?
