### ISSUE TITLE
DAR last modification date

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#3985]
Reported by @tdemalliard

> Lorsqu’un amendement est créé, modifié ou soumis, la date de dernière mise à jour du table des demandes n’est pas mise à jour. Cette date devrait reflèter  tout changement touchant la demande afin que le DAO puisse saisir facilement l’activité dans les demandes d’accès.
> 
> Ceci concerne donc aussi les ajouts de documents, commentaires entre chercheur et DAO, demande de faisabilité. Bref tout sauf les commentaires internes entre DAO et entrées privées au journal de la demande

**Comment by kazoompa** [comment]
I was not able to reproduce the problem upon, edition, document upload and submission; the corresponding DAR's last update date was changed. However, commenting does not affect the last update date.

**Comment by tdemalliard** [comment]
I did not check for every actions.

We received a notification for an amendment submitted, but the update date did not update, as shown on the screenshots, project 792980:

![image](https://user-images.githubusercontent.com/3911087/90775180-8c17e680-e2c6-11ea-9e55-c4cb6819bd0e.png)

![image](https://user-images.githubusercontent.com/3911087/90775249-9d60f300-e2c6-11ea-8186-e534c90dde95.png)

**Comment by ymarcon** [comment]
Events that do not set last-update datetime, although it should:

* any actions related to the feasibility forms
* any actions related to the amendment forms
* regular comment

Events that set last-update datetime, although it should not:

* action log entry
