### ISSUE TITLE
user account link does not keep profile language

### ISSUE THREAD

**Issue by tdemalliard** [obiba/mica2#3992]
**Describe the bug**
Mica language is set to French, user profile is set to French. But when clicking on 'compte utilisateur' button (user account) which lead to agate, the language switch to english.

**To Reproduce**
1. login with mica
2. language is set to FR
3. goto profile page
4. Profile language is set to French
5. click on button 'Compte utilisateur'
6. we arrive on agate part and the lang change for EN

**Expected behavior**
Language should stay FR

**Desktop (please complete the following information):**
 - docker mica 4.2.2
- docker agate 2.0
- chrome up to date on windows 10 up to date

![image](https://user-images.githubusercontent.com/3911087/92125704-4d595480-edcd-11ea-849e-9f2a712b31bb.png)

**Comment by ymarcon** [comment]
Is FR declared in Agate ?

**Comment by tdemalliard** [comment]
What do you mean?  FR in set in the profile of the user.

I will provide you more steps :
1. language in profile is set to FR
1. open incognito tap, browser and laptop is set to EN
2. goto https://sdas.cartagene.qc.ca : EN
3. login with the FR profile : lang switch to FR (profile language)
1. Click on name > profile : profile page open. FR (we are still on mica)
1. click on 'compte utilisateur' : we go to agate. EN
1. Agate display the profile page, display that preferred language is French, but page is displayed with EN

Agate is probably using the browser langage for this scenario instead of profile page, which is current mica language upon login.

**Comment by ymarcon** [comment]
I cannot reproduce: I have both EN and FR declared in Mica and Agate, my user prefers FR, my browser (and OS) default is in EN, when sign in mica it switch to FR, then from mica profile page to agate account page everything is in FR.

**Comment by ymarcon** [comment]
Ok, I am able to reproduce on mica-demo + agate-demo. Will investigate.

**Comment by tdemalliard** [comment]
Ok. DO you keep mica and agate demos up to date?

If so, I will try to reproduce there the  future bugs I may find.

**Comment by ymarcon** [comment]
It works on localhost because the servers share the cookie NG_TRANSLATE_LANG_KEY, whereas servers on different subdomains will not. Another issue I noticed is that when signin agate directly, the preferred lang is not set, this may be the real issue.
