### ISSUE TITLE
Cannot add a search criterion because Field cannot be entered

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#4042]
* go to one of the document configuration (networt, indiv study etc.)
* select search criteria editor
* add criterion
* fill-in form => as soon as a value is entered in the **Field** input, it is erased; criterion can never be saved

![image](https://user-images.githubusercontent.com/2581149/95453671-92901980-096b-11eb-9e11-30dbde4220e9.png)

**Comment by kazoompa** [comment]
The fields are based on the schema meaning that they should be preceded with `model.`.

**Comment by kazoompa** [comment]
The current implementation has the limit of being based on schema only. The current criterion for label is R/O and in the config file.

**Comment by ymarcon** [comment]
But there is no schema for a variable, then criterion addition should be disabled?

**Comment by kazoompa** [comment]
Yes.
