### ISSUE TITLE
Search's Named Documents Sets

### ISSUE THREAD

**Issue by meek0** [obiba/mica2#4058]
Currently, "Add to List" in Maelstrom's portal exists but Requires authentication..

- [x] Add to List button (Variables results)
- [x] Named document sets management page

**Comment by ymarcon** [comment]
Layout of the list page is to be revisited.

**Comment by meek0** [comment]
Do you have a design in mind?

**Comment by ymarcon** [comment]
Use the sidebar layout, for list display. One page per list, default redirects to first list.

**Comment by meek0** [comment]
will create: 
- a dynamic list link that will be of the form `/list/<listId>` where listId is the first one from the `/ws/variables/sets` resource
- a `/list/<listId>` controller for list pages

I think it would probably be a good idea for the server to prepare the link and the array of lists for every page (similar to it preparing the profile and such.

**Comment by ymarcon** [comment]
Please use an icon ([far fa-list-alt](https://fontawesome.com/icons/list-alt?style=regular)) for making this menu (aside of the cart one), not a ugly "Lists" menu entry.

**Comment by meek0** [comment]
/lists will either redirect to the first list id or to search if none are available.

**Comment by ymarcon** [comment]
I have just tried and it is confusing to go to the search page when there are no lists. I would have expected the list page with a message that tells that there is no list and a list can be created by blablabla.

**Comment by ymarcon** [comment]
Suggested improvements:
* list's sidebar:
  * highlight the menu of current list
  * add a badge with the count of items for each list menu
* list items management
  * empty list displays badly: make a list, delete all items of the list: bad datatable state (see how done for the cart)
* list creation
  * from the cart page, allow saving in a list (either existing or new one)
  * from the search page: 
    * the pencil button in the list creation form is confusing, would prefer a "+ Add"
    * pressing Enter in the list creation form does not do anything, would have expected the same as clicking on the form's button
    * creating a new list does not increment the list count in the navbar
* add a general config "Lists enabled" (requires to have "Cart enabled") because one could want cart but no lists

**Comment by ymarcon** [comment]
Make sure tht a not authenticated user is redirected to the signin page when clicking on the cart/list add button from the search page.

**Comment by ymarcon** [comment]
@meek0 Regression: when selecting some items in the cart or a list, and deleting them, all the items are removed (even the not selected ones).

**Comment by meek0** [comment]
I don't think there is any regression. I did not do any change to the `VariablesSetService.deleteVariables` function. it might be a genereal bug due to the fact that, when adding or deleting form/to a cart/list, an index event is sent.

I can create an issue regarding that if need be.

**Comment by ymarcon** [comment]
That bug was for a single item removal #4092, it's fixed
