### ISSUE TITLE
Search's Config to Hide/Disable Search Menu Items

### ISSUE THREAD

**Issue by meek0** [obiba/mica2#4060]

**Comment by ymarcon** [comment]
There are [settings for the columns](https://github.com/obiba/mica2/blob/master/mica-webapp/src/main/resources/_templates/libs/settings.ftl#L84-L87). Do you have something else in mind?

**Comment by meek0** [comment]
![image](https://user-images.githubusercontent.com/6180385/97587356-ad393980-19d1-11eb-88e9-85cda5830b12.png)
Notably the `Variables, Datasets, Studies, Networks` where, in MR's case, they'd want to hide the `Datasets` menu item as well as the its corresponding result tab while keeping the datasets sections enabled.

**Comment by kazoompa** [comment]
I have a solution that I will push shortly, this is only for the left menu that is in JS. As for the TABs, these tabs can be overridden in the FTL files.

**Comment by ymarcon** [comment]
Simple solution would be to add html element id attributes, so that a css rule or js script can handle each menu specifically.
