### ISSUE TITLE
Integration (CSS, Layout)

### ISSUE THREAD

**Issue by meek0** [obiba/mica2#4068]
[Maelstrom templates](https://github.com/maelstrom-research/mica-public-templates) overrides.

- [x]  Css Integration Font format/size/color and rules
- [x] Integration Headr menu
- [ ] Enhance Menu with page menu identification
- [x] Add Index page (Catalogue Drupal page)
- [ ] Add footer
- [ ] Search page Menu header + Footer integration
- [ ] Breadcom adaptation
- [ ] Text (Studies, Networks) page modification

**Comment by ymarcon** [comment]
If it is about Maelstrom only, move this issue to [maelstrom-research/mica-public-templates](https://github.com/maelstrom-research/mica-public-templates).

**Comment by meek0** [comment]
Moved to gitlab
