### ISSUE TITLE
Document Details Page Custumization

### ISSUE THREAD

**Issue by meek0** [obiba/mica2#4069]
- Study (individual, harmonization)
  - [x] add networks section
  - [ ] possibility to click on timeline to show DCE
  - [ ] stacked chart?
- Network
  - [x] #4054 
  - [x] #4055
- Dataset (collected, harmonized)
- Variable
  - [x] add variable type

Add to [Maelstrom templates](https://gitlab.com/maelstrom-project/maelstrom-public-pages) where appropriate.

**Comment by ymarcon** [comment]
Variable type is already in the title.
