### ISSUE TITLE
Truncating HTML text (objectives/description) in public pages breaks the rendering

### ISSUE THREAD

**Issue by kazoompa** [obiba/mica2#4080]
If an objective or description field contains a html text, truncating the text may remove a closing HTML tag and this will break the public page. Here is the code responsible:

```
<div class="marked">
   ${localize(std.objectives)?trim?truncate_w(200, "...")}
</div>
```

This bug is currently visible in Studies listing pages on Mlstr staging site. The Lines and Grid views are merged. To see the error, scroll down the page and grid items will appear.

Must find a way to truncate and ensure tags are closed or show the whole text. To investigate...

![image](https://user-images.githubusercontent.com/2814716/98291100-97e78080-1f78-11eb-8ee5-4054ba134795.png)

**Comment by ymarcon** [comment]
description is not in markdown ?

**Comment by kazoompa** [comment]
Yes, in Dataset documents.

Need to review [this code](https://github.com/obiba/mica2/blob/master/mica-webapp/src/main/resources/_templates/libs/scripts.ftl#L102-L107) and find a fix:

**Comment by kazoompa** [comment]
There may be some hope in this solution, try in [JSFiddle](https://jsfiddle.net/kazoompa/nq9w8bry/):

The idea is that `tidy()` will use the browser to normalize and tidy up the HTML text.
