### ISSUE TITLE
login error with safari

### ISSUE THREAD

**Issue by tdemalliard** [obiba/mica2#4097]
**Describe the bug**
Login with safari does not work, error 500 is displayed. But it works with chrome. I could not test it but I am also told that it does not work with firefox (version and OS unkown).

**To Reproduce**
1. use safari
1. goto signin page
2. enter login info
3. click sign in button
4. See error 500

**Expected behavior**
Login successful as with chrome

**Screenshots**
none

**Desktop (please complete the following information):**
 - macbook 
 - OS mojave
 - chrome 86.0.4240.198
 - safari 14.0
- mica 4.3.4

**Additional context**
mica login shows this when trying to login
```
2020-11-20 11:28:28.909  WARN 18 --- [qtp188917296-91] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved exception caused by handler execution: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported
```

Here is Safari developper tools request and response:
![image](https://user-images.githubusercontent.com/3911087/99825451-0e61b200-2b25-11eb-964c-c65ca76399b3.png)

And loading the index or singin page on safari show these 2 javascript errors: (no error on chrome)
![image](https://user-images.githubusercontent.com/3911087/99824844-3e5c8580-2b24-11eb-81da-85f28c0baf33.png)

**Comment by ymarcon** [comment]
Looks like "contains" is a js function name.

**Comment by ymarcon** [comment]
Works with Firefox on linux.

**Comment by ymarcon** [comment]
Probably because some JS engine are using non standard function contains() in place of (or in addition to) the standard [includes()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) one.
