### ISSUE TITLE
Change DAR ownership by DAO

### ISSUE THREAD

**Issue by tdemalliard** [obiba/mica2#4116]
**Is your feature request related to a problem? Please describe.**
Sometimes, researchers create a second account to start a new application. It can be a long time that they created their account and does not remember, or we created it for them when migrating to mica, or their new student start it...

Well, our DAO always notices these duplicates but cannot do anything to correct it and keep everything under the same account.

**Describe the solution you'd like**
The new feature: The DAO could have the ability to change the ownership of a DAR, with everything attached to it (comments, documents...). 

Then the administrator would delete this supplementary account via Agate (feature already present)

**Describe alternatives you've considered**
Editing by hand via a mongo editor. But it is very hard because there are lots of permissions.

**Comment by ymarcon** [comment]
Usage example:

`mica rest -u dao -p password -m PUT "/data-access-request/123456/_applicant?username=anotheruser"`
