### ISSUE TITLE
OpenJDK suppored?

### ISSUE THREAD

**Issue by mdc-webdb** [obiba/mica2#4155]
In the documentation only oracle java is written, but the oracle java is not free anymore.
Does work mica2 also with OpenJDK?

Thanks

**Comment by ymarcon** [comment]
Yes, Mica (and all Obiba software) works (and is developed) with OpenJDK. The only constraint is to use OpenJDK 8 (support of version 11 is a work in progress).

**Comment by mdc-webdb** [comment]
Thanks for the information. It will be nice when this will noted at the system requirements on all obiba products.

**Comment by ymarcon** [comment]
It is now :) thanks for your feedback.
