### ISSUE TITLE
[4.4.6]  Mica behind reverse proxy -> no client ip is loggend

### ISSUE THREAD

**Issue by tuxmaster5000** [obiba/mica2#4164]
When mica runs behind  an apache as an reverse proxy, not ip's of the real clients are logged.
Jetty itself can do this, but there exist no documentation for mica how to enable this.
In none of the log files (mica.log, rest.log, spring.log, stdout.log) any IP address will logged,

**Comment by ymarcon** [comment]
Remote IP added to rest.log messages (empty string if not identified).
