### ISSUE TITLE
Newly added boxes in forms not showing

### ISSUE THREAD

**Issue by M-Driessen** [obiba/mica2#4199]
I added a new box to the individual study form, but it is not showing up on the visible study overview.
Are newly added boxes supposed to not automatically show?

The newly added box is funding (second source)
![image](https://user-images.githubusercontent.com/79575366/124916133-9cc26f80-dff2-11eb-8dec-a1f057666b6a.png)

It is not visible on in the overview:
![image](https://user-images.githubusercontent.com/79575366/124915888-553be380-dff2-11eb-9098-909e721aa3d0.png)

Do we have to specify newly added boxes somewhere apart from the json code for the forms?

**Comment by ymarcon** [comment]
Hi, if you change the data model, you must modify its rendering accordingly. See documentation:
https://micadoc.obiba.org/en/latest/admin/pub-configuration.html

More specifically, in the case of an individual study, override the [studyDefinition macro](https://github.com/obiba/mica2/blob/master/mica-webapp/src/main/resources/_templates/libs/study.ftl#L61-L107) in the [models/study.ftl template](https://github.com/obiba/mica2/blob/master/mica-webapp/src/main/resources/_templates/models/study.ftl).

**Comment by M-Driessen** [comment]
Thanks for the quick response and explanation!
