### ISSUE TITLE
Add option to use identity provider for Mica

### ISSUE THREAD

**Issue by paulusv** [obiba/mica2#4200]
In Opal it is possible to use an identity provider for users to login. 
I wasn't able to find anything in the documentation about this, nor could I find anything in Mica settings.
I was wondering if something similar will be implemented for Mica, where users are able to login with an identity provider selected by admins.

**Comment by meek0** [comment]
Mica is heavily dependent on Agate for it's authentication process. See https://agatedoc.obiba.org/en/latest/web-user-guide/realms.html#open-id-connect-realm for more information.

**Comment by ymarcon** [comment]
This feature is available through Agate. Agate only manages user profile and delegates user authentication to the [OpenID provider](https://agatedoc.obiba.org/en/latest/web-user-guide/realms.html#open-id-connect-realm) of your choice. From Mica point of view, it adds "Signin with" and "Signup with" buttons.
