### ISSUE TITLE
ordering of datasets broken

### ISSUE THREAD

**Issue by joerghenkebuero** [obiba/mica2#4203]
**Describe the bug**
When using the cards tab in the overview of available datasets, the order button has no effect on the order of the displayed datasets. 

**To Reproduce**
We have renamed datasets to Instruments: https://mica.covid19.studyhub.nfdi4health.de/datasets?query=dataset(limit(0,50),sort(name))

**Expected behavior**
The filtering of the datasets should work (on Name, Alphabetical or Chronoligical). The ordering should stick to the displayed names, not the the internal ones.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/69628891/125244268-69802900-e2ef-11eb-8f26-ccbf6a97e9dd.png)

**Desktop (please complete the following information):**
 - OS: doesn't matter
 - Browser: firefox 78.11.0esr (64-Bit)
 - Version MICA 4.5.5

**Comment by kazoompa** [comment]
I do not see the the problem, when I sort on Name ASC/DESC the result changes accordingly (see below). However, I see the bug when user lands on the same page with a descending order, the interface seems not to account for the order in the URL.


ASC Order:
![image](https://user-images.githubusercontent.com/2814716/125283513-7d735d00-e2e6-11eb-8b0d-779ea109ea7a.png)

DESC Order:
![image](https://user-images.githubusercontent.com/2814716/125283570-8cf2a600-e2e6-11eb-8640-ba1250979f95.png)

**Comment by joerghenkebuero** [comment]
thank you for your feedback. However, I still cannot reorder the cards. Have you used the described firefox browser on a linux system? As far as I know, also on Windows it seems not to work. Any suggestions?

**Comment by kazoompa** [comment]
I tried on Chrome, FireFox and Edge on Windows but I am still able to sort the listing. Do you see any errors in the browser console (press CTRL-SHIFT-J)?

**Comment by joerghenkebuero** [comment]
> Do you see any errors in the browser console (press CTRL-SHIFT-J)?

No, I didn't see any errors there. I could find an ajax request and an response that fits to the display, but still not sorted. Maybe a conference would be helpful to seek the bug? If so, can you send me an invitation by mail for tomorrow?

**Comment by kazoompa** [comment]
We have a new release for Mica (4.5.8), please try this and make sure your browser cache is emptied prior to testing.

**Comment by joerghenkebuero** [comment]
> We have a new release for Mica (4.5.8), please try this and make sure your browser cache is emptied prior to testing.

This has solved the bug, thank you very much.

**Comment by kazoompa** [comment]
Great!
