### ISSUE TITLE
old dar cannot be seen and cannot add amendments

### ISSUE THREAD

**Issue by tdemalliard** [obiba/mica2#4213]
**Describe the bug**
An account from mica Drupal era cannot see his approved DAR.

After correction via mongodb, he sees and access his approved DAR but he cannot add amendment.

**To Reproduce**
Not sure about that, maybe upgrade from and old version with users and DARs  to newer one. User can login but cannot see its passed DARs. After fixing via mongodb, cannot add amendment either.

**Expected behavior**
old DARs should still be accessed, amendment should be working with them.

**Desktop (please complete the following information):**
 - mica2 version 4.3
 - agate 2.0

**Additional context**
Solving access/view: change user name for email in mongodb mica2/subjectAcl

Maybe it is the same to solve amendment : add persmissions in subjectAcl

**Comment by meek0** [comment]
It is related to the associated permission in subjectAcl. The solution would be to change the applicant of the data access request to the applicant's username.

We have an API for that:
`curl -X PUT <MICA_URL>/ws/data-access-request/<DAR_ID>/_applicant -H "Accept: application/json" -G -d username="<NEW_APPLICANT_USERNAME>" -u<ADMIN_USER>`

This should cascade through the amendments.

**Comment by tdemalliard** [comment]
Any chance that you got an api command to go through every dar to check and change the applicant  if necessary?

**Comment by meek0** [comment]
No API for that unfortunately, Mica itself have the full profile in it's database (Agate provides it when the user has logged in successfully).

The strategy would be to find all DAR's, filter out those that don't have an applicant email and map those that do to the correct username.

**Comment by tdemalliard** [comment]
No problem. I have already sorted out that list via R script. So I will iterate through this list and its done!

To be sure about this batch update : Could you confirm that subjectACL should use the email instead of the username?

**Comment by meek0** [comment]
It should use the username.

**Comment by tdemalliard** [comment]
In user collection from agate database :
* _id = the_username
* name = the_username
* email = name@email.com

In subjectACL:
* dar can be accessed if I change `the_username` to `name@email.com`

So the email seems to be the key between the user and the dar via subjectACL.

Could this be an issue from my older version with could be resolved if I upgrade?

**Comment by meek0** [comment]
A Mica upgrade (if you are not already on the latest release) would only make sure that new DARs will always be associated to the applicant's username.

Problem is due to the fact that during the drupal days, applicants who logged in using their email had that associated to their DAR instead of the username.

**Comment by tdemalliard** [comment]
Ok thanks. I will day as you said earlier for a quick fix, and I will plan
an upgrade at a more convenient time.

Thank you for your help. Thibault
