### ISSUE TITLE
VueMicaSearch.css not found

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica2#4250]
There is this import: [search.ftl#L9](https://github.com/obiba/mica2/blob/master/mica-webapp/src/main/resources/_templates/search.ftl#L9). Is it a legacy?

```
GET https://mica-demo.obiba.org/assets/libs/node_modules/vue-mica-search/dist/VueMicaSearch.css 
  net::ERR_ABORTED 404
```

**Comment by meek0** [comment]
Looks like vue-mica-search does not add built css in dist. Will see if still relevant.
