### ISSUE TITLE
Archiving DAR : doable regardless it status, and disable notifications

### ISSUE THREAD

**Issue by tdemalliard** [obiba/mica2#4290]
**Is your feature request related to a problem? Please describe.**
Currently, we can archive a DAR only if approved or rejected. If the project is not over while archived, notifications for report continue.

**Describe the solution you'd like**
We would like to archive a DAR regardless its status. Archive means for us that the project is over as agreed between us and the researcher, even though an amendment is open, even though the date of end or project is not reached, even though the DAR was never submitted. 

That would be also great if there is any information on the dashboard if the project is archived.

That would be also great to have an archiving entry in the historic section.

**Describe alternatives you've considered**
None, we handle closed project with an excel file.

**Additional context**
None

**Comment by tdemalliard** [comment]
How do I close an open DAR ?

Here, for example I am DAO and there is an open DAR. I would like to archive it because the researcher does not want to move forward with this project, but the archive button is not showing : 
![image](https://user-images.githubusercontent.com/3911087/157268446-ee7ab7f1-49f9-4dc0-a913-e80927789749.png)

**Comment by kazoompa** [comment]
If you go to the Administration of DARs, under **Other **Settings**, do you have **Grant Edit Permission to Data Access Officers.** checked? Maybe you can simply approve the DAR along with a comment/action.

**Comment by tdemalliard** [comment]
I have just check it, empty cache via admin panel, but I cannot see any "Approve" button  as DAO (but with Admin). I agree that we can do something manually with the historic tab.

But this is not a satisfying solution because approving a DAR to archive it has not the same meaning as archive an unapproved DAR. Then, it will contribute to our approved DAR list. In other words :
* An archived DAR means that the DAR is closed, whether it is approved or not, whether end project date is reached or not.
* An approved DAR means that a committee authorized the project and CARTaGENE (our group) has sent data and/or samples.

What do you think?

**Comment by tdemalliard** [comment]
Great, thank you. You and Yannick can reach for me anytime on Slack, email or here.
