### ISSUE TITLE
[4.6.6] mica listen on * interface for the https port

### ISSUE THREAD

**Issue by tuxmaster5000** [obiba/mica2#4292]
For the http port, via address settings the listen interface can be configured, but this is missing for the https settings.
This will needed, when the TLS termination is done by an apache for example in local host front of mica.
Or an setting to disable the https listening.
But nothing of it is noted in the documentation:
https://micadoc.obiba.org/en/latest/admin/configuration.html

**Comment by ymarcon** [comment]
This has not been released yet: https://github.com/obiba/mica2/commit/cb4b09f0711743394ac8ae85f7fd0fcb2a0d3582

**Comment by tuxmaster5000** [comment]
Thanks for the information.
