### ISSUE TITLE
Amendment ID creation needs to ensure uniqueness 

### ISSUE THREAD

**Issue by kazoompa** [obiba/mica2#4293]
- Create a DAR and follow the workflow until the approval
- Create a few AMDs

Usually the ID of AMDs are DAR-A1, DAR-A2, DAR-A3

- Delete DAR-A2
- Try to Create a new AMD

Result: Error 500 due to the fact that the new AMD ID is based on the # of current AMDs, hence AMD-A3 but this ID is already used. Need to ensure creation of a unique ID.

Mica version bug was found: 4.5.5

**Comment by ymarcon** [comment]
Will be available in next 4.6 patch release.
