### ISSUE TITLE
Security issue - .htaccess is not protected

### ISSUE THREAD

**Issue by jonathanmasseurca** [obiba/mica2#4310]
Describe the bug
You can download the .htaccess
https://your/ server/.htaccess/ (With the / at the end)

To Reproduce

Go to '...' https://your/ server/.htaccess/ (With the / at the end)
You will see the server .htaccess
Expected behavior
.htaccess should be keep protected.

Desktop (please complete the following information):

OS: Windows 11
Browser Chrome
Version 102

**Comment by ymarcon** [comment]
I am not sure it is used. Can you verify that @kazoompa ?

**Comment by kazoompa** [comment]
I will take a look...

**Comment by kazoompa** [comment]
I was able to reproduce the download but I do not think there is any security issues since access to data is through Mica's authorization layer and permission system.

Unfortunately, this file cannot be removed as it affects the service loading. I will explore using filters to block this.

**Comment by jonathanmasseurca** [comment]
Thank you @kazoompa

Yes, a filter should be perfect to fix the issue, the issue was our security system (Tenable) that scan all services for vulnerability was doing an alert about the .htaccess.
