### ISSUE TITLE
New Graviton 2 server arm64

### ISSUE THREAD

**Issue by jonathanmasseurca** [obiba/mica2#4379]
**Is your feature request related to a problem? Please describe.**
We are upgrading our main server to a Graviton 2.

The only thing that is not compatible with the server is the Obiba suite.

We can run R studio and everything else without any issue.

I also tried to run docker but the only compatible platform is x64
https://hub.docker.com/r/obiba/mica/tags

**Describe the solution you'd like**
To have an obiba version that can run on Linux arm64

**Additional context**
The arm64 CPU are becoming more popular for powerful computer / server and mac (M1, M2) etc.

Many thanks for your help,

**Comment by ymarcon** [comment]
What do you need to make it work on Graviton 2?

**Comment by jonathanmasseurca** [comment]
A maelstrom version that can run arm64

Is there another arm64 repo available to install the mica package?

**Comment by ymarcon** [comment]
Ok, but it is a java application, then if java runs, opal/mica/rock should run as well.
What issue do you have?

**Comment by jonathanmasseurca** [comment]
When I try to install it using apt-get install agate or mica2 or opal I have this issue : 

N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://obiba.jfrog.io/artifactory/debian-local all InRelease' doesn't support architecture 'arm64'

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package opal

It say that it doesn't support arm64

**Comment by jonathanmasseurca** [comment]
my file : /etc/apt/sources.list.d/obiba.list

is : 
deb [arch=arm64 signed-by=/usr/share/keyrings/obiba.gpg] https://obiba.jfrog.io/artifactory/debian-local all main

**Comment by ymarcon** [comment]
Hmm "all" means all, including arm64.

**Comment by jonathanmasseurca** [comment]
I changed the line (replaced the arm64 to amd64) : 

deb [arch=amd64 signed-by=/usr/share/keyrings/obiba.gpg] https://obiba.jfrog.io/artifactory/debian-local all main

Not sure but it seems to work now. It has found the arm64 package.

I will run more test but it installed succesfully.
