### ISSUE TITLE
[5.1.0] Security flags at the cookies are missing.

### ISSUE THREAD

**Issue by tuxmaster5000** [obiba/mica2#4395]
Our security scanner has detected, that the secure and HttpOnly flag is missing at the _uid cookie.
Can you fix it?

Sample:
nmap -p 443 <Hostname>  --script http-cookie-flags  --script http-headers
...
|   Set-Cookie: _uid=307343fb-efd1-42ba-87c0-dfee9d8e1652
...

Thanks

**Comment by ymarcon** [comment]
See [Reverse proxy recommended settings (headers section)](https://micadoc.obiba.org/en/latest/admin/configuration.html#reverse-proxy-configuration).

**Comment by ymarcon** [comment]
That is true that the `HttpOnly` flag should be enforced for this cookie. In the meantime you should use the workaround above (which does a bit more than setting `HttpOnly` flag, then it is still the recommended approach).
