### ISSUE TITLE
Docker - mica - logout

### ISSUE THREAD

**Issue by massej** [obiba/mica2#4423]
### This issue is unique

- [X] I have used the [search tool](https://github.com/obiba/mica2/issues?q=) and did not find an issue describing my bug.

### Version information

5.2.3

### Expected behavior

Logout should work

### Actual behavior

In mica 5.2.3 using docker, the agate url is replaced by the docker agate hostname which is not the valid hostname.

(https://github.com/obiba/mica2/blob/bf9efc77d48a6414594b38b1a8356c564ec7a6ce/mica-webapp/src/main/java/org/obiba/mica/web/controller/SignController.java#L138)

It will be replaced by https://obiba-agate:8444/ so the logout will never work in a docker.

### Reproduction steps

1. Login into mica
2. Use the logout on the right

<img width="237" alt="image" src="https://github.com/obiba/mica2/assets/22155257/9ce0ec53-92bd-444d-9009-dc46e34077e8">

The sign out will try to go to https://obiba-agate:8444/

### Operating System (OS)

Linux

### Browser

Google Chrome

**Comment by kazoompa** [comment]
Hi,

[Mica Demo](https://mica-demo.obiba.org) also is a docker container and configured via a `docker-compose` and this issue does not exist.

Please provide more information regarding your setup and OBiBa stack configuration.

Best,

**Comment by massej** [comment]
AGATE_URL : https://obiba-agate:8444 

We are using a WAF (web application firewall) for our Docker and we cannot do a loop back using the same URL. (i.e. we cannot use the external link from a container), so we cannot do AGATE_URL : https://agate.mydomain.com

**Comment by massej** [comment]
We changed our hosts file in the docker and it point to an internal reverse proxy so the https communication stay internal and the WAF is not blocking it.
