### ISSUE TITLE
Mica -> Agate -> OpenID support

### ISSUE THREAD

**Issue by tuxmaster5000** [obiba/mica2#4433]
The OpenID path for  Opal -> Agate -> OpenID will work, but the same for 
Mica -> Agate -> OpenID it looks like missing, because the login on mica fails, when Agate use OpenID for the user authorisation.

**Comment by ymarcon** [comment]
I need more information here about what does not work, because Mica always uses Agate as its ID provider, and OpenID delegation will also happen (except that it shows up in Mica pages).

**Comment by tuxmaster5000** [comment]
In which version will it be fixed?

**Comment by ymarcon** [comment]
In version 5.0, still in development (java 21, spring 6 upgrade etc). Agate 3.0 (similar upgrades) is almost ready to be released.
